/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { FunctionCall } from '../state';
import { FunctionResponseScheduling } from '@google/genai';

export const mannerismTool: FunctionCall = {
  name: 'emit_mannerism',
  description: 'Emits a common Filipino/Taglish mannerism, expression, slang, or interjection to add authentic character flavor. Use these to react, agree, tease, or fill silence naturally.',
  parameters: {
    type: 'OBJECT',
    properties: {
      phrase: {
        type: 'STRING',
        description: 'The specific expression or mannerism to say.',
        enum: [
          'weh',
          'edi_wow',
          'ano_ba_kasi',
          'yes_question',
          'abah_abah',
          'hay_nako',
          'grabe_ka',
          'kaya_mo_yan',
          'syempre',
          'sige_na_nga',
          'luh',
          'omsim',
          'charot',
          'anyare',
          'ganern',
          'wait_lang',
          'joke_lang',
          'awit',
          'sana_all',
          'sure_ka',
          'talaga_ba',
          'di_nga',
          'oo_nga',
          'ay_grabe',
          'hala',
          'yieee',
          'naks',
          'boom',
          'aray',
          'sus',
          'che',
          'ewan_ko_sayo',
          'bahala_ka',
          'gets',
          'kuha_mo',
          'sayang',
          'badtrip',
          'astig',
          'petmalu',
          'werpa',
          'lodi',
          'basic',
          'easy',
          'g',
          'tara',
          'game',
          'pass',
          'bounce',
          'gege',
          'copy',
          'roger',
          'noted',
          'nice',
          'solid',
          'goods',
          'oks',
          'keri',
          'push',
          'bet',
          'ayaw',
          'gusto',
          'pwede',
          'bawal',
          'siguro',
          'baka',
          'depende',
          'ewan',
          'sige',
          'naman',
          'pala',
          'nga',
          'din',
          'lang',
          'muna',
          'pa',
          'na',
          'yata',
          'raw',
          'daw',
          'kasi',
          'kaya',
          'pero',
          'habang',
          'basta',
          'agad',
          'parang',
          'medyo',
          'sobra',
          'sakto',
          'kulang',
          'labo',
          'malabo',
          'klaro',
          'ayos',
          'gulo',
          'hassle',
          'chill',
          'relax',
          'kalma',
          'wait',
          'teka',
          'sandali',
          'ayun_lang',
          'yun_na_nga',
          'ganun_talaga',
          'wala_eh',
          'meron_pa',
          'tapos',
          'ano_pa',
          'seryoso',
          'pramis',
          'peksman',
          'huwag_kang_ganyan',
          'tigilan_mo_ko'
        ]
      }
    },
    required: ['phrase']
  },
  isEnabled: true,
  scheduling: FunctionResponseScheduling.INTERRUPT,
};